### ISSUE TITLE
Move HttpClientSlim to Testing repo

### ISSUE THREAD

**Issue by cesarbs** [aspnet/MetaPackages#102]
HttpClientSlim was copied from Kestrel to unblock the CI. The proper fix is to move it to Testing and have both Kestrel and MetaPackages consume it from there.

**Comment by muratg** [comment]
Can it be a "Common" repo shared source thing, instead of a separate package?

**Comment by cesarbs** [comment]
What is the problem with having it in the Testing repo/package? Note that this is only used in tests.

**Comment by muratg** [comment]
Testing package should be fine. I assumed you wanted to create a new package just for this.

**Comment by cesarbs** [comment]
Testing PR:

https://github.com/aspnet/Testing/pull/280

Reaction PRs:

https://github.com/aspnet/KestrelHttpServer/pull/1917

https://github.com/aspnet/MetaPackages/pull/176
