### ISSUE TITLE
Deps file and lightup bugs

### ISSUE THREAD

**Issue by glennc** [aspnet/MetaPackages#108]
Listing out bugs as I find them setting up another e2e.

- [x] HostingStartup.Template is being included in the lightup deps file.
- [x] Microsoft.CSharp 4.3.0 is being resolved and cannot be found.

@muratg

**Comment by JunTaoLuo** [comment]
The other issue should be fixed by https://github.com/aspnet/MetaPackages/pull/110

**Comment by pakrym** [comment]
Verified deps files in latest build, they don't have Microsoft.CSharp runtime dll
