### ISSUE TITLE
Metapackage for 1.0.4 patch release

### ISSUE THREAD

**Issue by muratg** [aspnet/MetaPackages#11]
Bump up the dependencies that we're releasing as part of this patch release.

cc @Eilon @DamianEdwards

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/MetaPackages/commit/469dd3e8ff754bbac69f4246a68e6bf36563d31e
