### ISSUE TITLE
Add WebHost.CreateDefaultBuilder<TStartup>(args)

### ISSUE THREAD

**Issue by danroth27** [aspnet/MetaPackages#112]
All of our templates create the default builder and then call `UseStartup<Startup>`. We should consider just making this a one-liner

**Comment by muratg** [comment]
@DamianEdwards do you want this in 2.0.0?

**Comment by JunTaoLuo** [comment]
There's a community PR for this though it contains additional extensions as well: https://github.com/aspnet/MetaPackages/pull/152

**Comment by muratg** [comment]
@JunTaoLuo Looks like that PR is dead.  When you get the time, could you pick this method only for now and check-in?  

@DamianEdwards @davidfowl FYI.

**Comment by JunTaoLuo** [comment]
Merged in https://github.com/aspnet/MetaPackages/commit/07bf8d02a054e37461c8ccf50dc95ee594556c62 and https://github.com/aspnet/MetaPackages/commit/7ec8cc5fadd14fbe755fb978eedec933f674f887
