### ISSUE TITLE
Make KestrelServerOptionsSetup public

### ISSUE THREAD

**Issue by andrewlock** [aspnet/MetaPackages#113]
Is there any reason `KestrelServerOptionsSetup` is `internal`, not `public`?

Currently, if you wish to tweak the setup made by `ConfigureDefaultBuilder`, you can copy and paste the whole method into your own app, with the exception of the final call on the `IWebHostBuilder`: 

```
.ConfigureServices(services =>
                {
                    services.AddTransient<IConfigureOptions<KestrelServerOptions>, KestrelServerOptionsSetup>();
                });
```

Just making `KestrelServerOptionsSetup` public would make copy-paste feasible. I can't see any reason why it would be a problem?

**Comment by davidfowl** [comment]
What do you want to tweak?

**Comment by andrewlock** [comment]
Most likely is changing the `ConfigureAppConfiguration` method

**Comment by davidfowl** [comment]
I'm not sure why you need `KestrelServerOptionsSetup` exposed for that. Can you elaborate?

**Comment by andrewlock** [comment]
Sure, I may be missing something obvious here!

I create a new project from a template that uses the `CreateDefaultBuilder` helper. Say I want to keep everything setup as in the default builder, but remove the console logger and replace with something else. 

I assume, if I want everything else the same I basically have to copy and paste the `CreateDefaultBuilder` method, and edit the `ConfigureLogging` method, so my Program would look something like: 

```c#
public class Program
{
    public static void Main(string[] args)
    {
        BuildWebHost(args).Run();
    }

    public static IWebHost BuildWebHost(string[] args) =>
        CreateCustomBuilder(args)
            .UseStartup<Startup>()
            .ConfigureAppConfiguration((hosting, config) => {hosting.})
            .Build();
    
    public static IWebHostBuilder CreateCustomBuilder(string[] args)
    {
        var builder = new WebHostBuilder()
            .UseKestrel()
            .UseContentRoot(Directory.GetCurrentDirectory())
            .ConfigureAppConfiguration((hostingContext, config) =>
            {
                var env = hostingContext.HostingEnvironment;

                config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                        .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);

                if (env.IsDevelopment())
                {
                    var appAssembly = Assembly.Load(new AssemblyName(env.ApplicationName));
                    if (appAssembly != null)
                    {
                        config.AddUserSecrets(appAssembly, optional: true);
                    }
                }

                config.AddEnvironmentVariables();

                if (args != null)
                {
                    config.AddCommandLine(args);
                }
            })
            .ConfigureLogging((hostingContext, logging) =>
            {
                logging.UseConfiguration(hostingContext.Configuration.GetSection("Logging"));
                /* Customise logging here*/
            })
            .UseIISIntegration()
            .UseDefaultServiceProvider((context, options) =>
            {
                options.ValidateScopes = context.HostingEnvironment.IsDevelopment();
            })
            .ConfigureServices(services =>
            {
                services.AddTransient<IConfigureOptions<KestrelServerOptions>, KestrelServerOptionsSetup>();
            });

        return builder;
    }
}
```

But that won't compile, as `KestrelServerOptionsSetup` is internal. 

It looks like you could probably just duplicate the `KestrelServerOptionsSetup` in your app too, but it seems like making it public would make sense?

**Comment by davidfowl** [comment]
The fact that you need to copy everything is smelly though right. It might be better to replace the ILoggerFactory with your own instance.

**Comment by andrewlock** [comment]
Oh yeah, totally smelly, but if you want to customise anything this method uses, it's the only option really right? And I thought that was the suggestion - use this method if it matches your requirements, otherwise just write your own `WebHostBuilder`. So if I want to have the Kestrel config loaded using Configuration, and `KestrelServerOptionsSetup` was public, you could just do something like 

```c#
new WebHostBuilder()
    .AddKestrel()
    .ConfigureServices(services =>
    {
        services.AddTransient<IConfigureOptions<KestrelServerOptions>, KestrelServerOptionsSetup>();
    });
```

Obviously it's not a big issue if making `KestrelServerOptionsSetup` `public` isn't an option - I can always copy the class code into my app`, but it would be convenient not to have to!

**Comment by davidfowl** [comment]
Sure, it can be made public. Most of the things in that method are overridable from the outside that's why we don't consider it a big deal. Are you just wanting to configure kestrel using a configuration file? 

What exactly are you trying to do?

**Comment by andrewlock** [comment]
When you say "overridable" from the outside - I can see that you can add extra config and logging delegates, but you can't remove/replace the ones added by the `CreateDefaultBuilder`  can you?

TBH, I'm just playing with it atm, and that was just something I noticed. I liked the demo of setting SSL and Kestrel setup in appsettings.json, and I can see people wanting to do something similar, without necessarily using `CreateDefaultBuilder`

**Comment by davidfowl** [comment]
> When you say "overridable" from the outside - I can see that you can add extra config and logging delegates, but you can't remove/replace the ones added by the CreateDefaultBuilder can you?

Some things can be replaced others can't.

> I liked the demo of setting SSL and Kestrel setup in appsettings.json, and I can see people wanting to do something similar, without necessarily using CreateDefaultBuilder

I'd like to wait to see how many people need this before moving it somewhere else and making it public.

**Comment by davidfowl** [comment]
This meta package is about opinionated defaults. It can also assume things because it depends on everything else. That's the reason that Kestrel doesn't have this configuration based API and why you can't get it without referencing the meta package.

**Comment by muratg** [comment]
Moving to Backlog per @davidfowl's comment above. If we get enough people needing this, we can consider later.

**Comment by valleyspirit** [comment]
How do I remove .AddConsole() and .AddDebug() and logging in general, or JSON file configuration, if I will not be able to create an IWebHost or WebHostBuilder myself which has the same Kestrel options as the default? How do I do something as simple as remove the server header from Kestrel? It appears that re-implementing or removing simplistic or redundant code which is never going to be used, just became more difficult. I hope it is still possible. I sympathize with andrewlock and any tips for creating a Kestrel-complete IWebHost config of my own, are welcome, thx!

**Comment by davidfowl** [comment]
> How do I remove .AddConsole() and .AddDebug() and logging in general,

https://github.com/aspnet/Logging/pull/659/files

> or JSON file configuration, 

https://github.com/aspnet/Configuration/pull/683

> How do I do something as simple as remove the server header from Kestrel? It appears that re-implementing or removing simplistic or redundant code which is never going to be used, just became more difficult

Options composes, so you can do something like: 

```C#
services.ConfigureOptions<KestrelServerOptions>(o =>
{
   o.AddServerHeader = false;
});
```

> I sympathize with andrewlock and any tips for creating a Kestrel-complete IWebHost config of my own, are welcome, thx!

What exactly do you want to do that can't be done?

**Comment by xperiandri** [comment]
Why do you need that if it is being registered when `UseKestrel(options => options)` called?
See [WebHostBuilderKestrelExtensions.cs](https://github.com/aspnet/KestrelHttpServer/blob/9515b617f165ccb46f5b8d6c94809586a1eb50b3/src/Microsoft.AspNetCore.Server.Kestrel/WebHostBuilderKestrelExtensions.cs)

**Comment by andrewlock** [comment]
@xperiandri This has apparently all changed since I raised the issue! 😄 

[Previously](https://github.com/aspnet/MetaPackages/blob/rel/2.0.0-preview1/src/Microsoft.AspNetCore/WebHost.cs), the WebHost.CreateDefaultBuilder() call explicitly called 

```
.ConfigureServices(services =>
                {
                    services.AddTransient<IConfigureOptions<KestrelServerOptions>, KestrelServerOptionsSetup>();
                });
```

and WebHostBuilderKestrelExtensions.cs didn't do that for you, so there was no way of using it without using the default builder. A bunch of things appear to have moved since then - the `KestrelServerOptionsSetup` to the Kestrel repo, the `CertificateLoader` to the hosting repo, so I think this issue is probably null and void.

Feel free to close it @davidfowl

**Comment by xperiandri** [comment]
Ah @andrewlock, then you did a good job.
By the way your articles are useful.
