### ISSUE TITLE
Improve certificate binding for Kestrel & support for Update-Database.

### ISSUE THREAD

**Issue by blowdart** [aspnet/MetaPackages#114]
Right now it gets the certificate by subject name, and chooses the one whose expiry is furthest in the future. However it doesn't check the purposes, or EKU so you could end up with a certificate which, whilst still valid in terms of expiry, is not valid for HTTPS binding.

In addition the setup, with the current Individual Auth templates, breaks Update-Database through the package manager window because this runs in a production environment, and there is not production config. So, when Update-Database attempts to run through whatever initialization it uses it hits the kestrel certificate setup, can't find any configuration and throws

```
System.InvalidOperationException: Unable to configure HTTPS endpoint. For information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054. ---> 
System.Collections.Generic.KeyNotFoundException: No certificate named 'HTTPS' found in configuration for the current environment (Production).
```

Even when you manually copy the development config to production.config to get your database created you end up with another error from data protection.

```
PM> Update-Database 
rosoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
Update-Database : Exception calling "Substring" with "1" argument(s): "StartIndex cannot be less than zero.
Parameter name: startIndex"
At line:1 char:1
+ Update-Database
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Database], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException,Update-Database
```

So right now a new user is going to be blocked when starting a new project.

**Comment by danroth27** [comment]
@bricelam for the Update-Database part of this issue.

**Comment by blowdart** [comment]
On the selection of certs for HTTPS - it's valid to have a cert which no subject, in fact, if a SAN property is there the subject should be ignored. This doesn't matter in the selection for Identity as a Service, because it's not used for HTTPS.

So the selection should be "Give me all certs which I can used for HTTPS, based on their EKU - 

```
Server Authentication (1.3.6.1.5.5.7.3.1)
Client Authentication (1.3.6.1.5.5.7.3.2)
```

and key usuage

```
Digital Signature (80)
```

And then filter based on either the correct DNS name appearing as one entry in the SAN, or, if that doesn't match, a subject name

**Comment by blowdart** [comment]
Or, as an option give either

1. Thumbprint lookup
1. Serial Number lookup

**Comment by danroth27** [comment]
This issue was moved to aspnet/KestrelHttpServer#1880
