### ISSUE TITLE
Concern with AddConsole in WebHost.CreateDefaultBuilder

### ISSUE THREAD

**Issue by achandlerwhite** [aspnet/MetaPackages#115]
I didn't see this mentioned anywhere here or over in the Logging repo. Looks like the new WebHost.CreateDefaultBuilder method adds a console logger... but for production scenarios isn't the console logger really slow? I know the logger was improved to use a background thread, but the perf metrics mentioned over in the logging repo [here ](https://github.com/aspnet/Logging/pull/551) don't seem to indicate a speedup.

Am I missing something? Thanks!

**Comment by Tratcher** [comment]
There's a distinction between adding it and turning it on. The logging configuration is used to determine how much actually gets logged and to what destinations.

**Comment by achandlerwhite** [comment]
Tratcher, thanks for your reply. I'll make sure to config the console logging provider to LogLevel.None for Production environments.

**Comment by achandlerwhite** [comment]
I'll make sure to set the Console's default LogLevel to LogLevel.None for Production environments.
The approach differs somewhat from the 1.x approach where I can completely avoid adding the unneeded provider--but I guess that is to be expected.
