### ISSUE TITLE
Add Microsoft.EntityFrameworkCore.ApplicationInsights

### ISSUE THREAD

**Issue by bricelam** [aspnet/MetaPackages#116]
@glennc said we may or may not need to do this...

**Comment by muratg** [comment]
@glennc What do we do with this one?  Include in the metapackage?  Runtime Package Store? Elsewhere?

**Comment by JunTaoLuo** [comment]
Making package as noship/exclude for now since it's not ship ready.

**Comment by JunTaoLuo** [comment]
Marked as noship/exclude for now.
