### ISSUE TITLE
Metapackage for 1.1.1 patch release

### ISSUE THREAD

**Issue by muratg** [aspnet/MetaPackages#12]
Bump up the dependencies that we're releasing as part of this patch release.

cc @Eilon @DamianEdwards

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/MetaPackages/pull/16
