### ISSUE TITLE
Add HostingStartup packages to .All

### ISSUE THREAD

**Issue by Tratcher** [aspnet/MetaPackages#125]
https://github.com/aspnet/AzureIntegration/issues/54
Microsoft.AspNetCore.ApplicationInsights.HostingStartup
Microsoft.AspNetCore.AzureAppServices.HostingStartup

Should be added to Microsoft.AspNetCore.All. This will reduce the likelyhood of version conflicts.

Should it use PrivateAssets=compile?

**Comment by anurse** [comment]
We need to verify:

1. that HostingStartup all works with this change
2. that the APIs provided by HostingStartup dependencies (i.e. App Insights) are **not** available to the app at compile time
3. that if the app does directly reference App Insights, the APIs **do** become available at compile time.

**Comment by muratg** [comment]
@Tratcher is this good to close?

**Comment by Tratcher** [comment]
It still needs one manual end-to-end verification. That's really only possible via updated templates. Do we have a template build with this in it yet?
