### ISSUE TITLE
Remove dotnet-archive and Microsoft.DotNet.Archive from metapackages

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/MetaPackages#130]
These are clones of the tool from the dotnet/cli builds. We should be consuming their tools or build ours periodically in case we need updates. These tools do not belong in the metapackages repo and we should remove them.

cc @anurse

**Comment by JunTaoLuo** [comment]
cc @NTaylorMullen, we plan to remove these packages so I don't think there's anything required regarding sha256

**Comment by muratg** [comment]
This wouldn't impact product code, just the tools so I think we can do this at the end of 2.0.0 (lower pri.) If we can't get to it, it's fine to do it later as well.
