### ISSUE TITLE
Re-enable symbols generation during dotnet restore

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/MetaPackages#135]
Need to find out why we are running into the error 

```
Unable to load Microsoft.DiaSymReader.Native.amd64.dll.  Please ensure that Microsoft.DiaSymReader.Native.amd64.dll is on the path.  Error='126'
Error generating PDB for 'C:\gh\MetaPackages2\src\Microsoft.AspNetCore.RuntimeStore\bin\work\Build.RuntimeStore.References_2.0.0-preview2--\runtimopt\SQLitePCLRaw.core.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

and revert https://github.com/aspnet/MetaPackages/pull/134

**Comment by JunTaoLuo** [comment]
According to @eerhardt, we need to run this build from the developer command prompt or put the Microsoft.DiaSymReader.Native.amd64.dll on the path.

**Comment by gkhanna79** [comment]
Diasymreader is the dependency that is used to generate PDBs. Like any dependency, it needs to be in a location where OS loader can find it. Path is one of the options.

**Comment by JunTaoLuo** [comment]
Added DiaSymReader to the path to enable symbol generation and updated build to avoid long path issues.
