### ISSUE TITLE
Microsoft.AspNetCore.All can be installed into net461 project without error

### ISSUE THREAD

**Issue by anurse** [aspnet/MetaPackages#142]
Repro Steps:

1. Create new .NET Console Core app
2. Change target framework to `net461`
3. Add reference to `Microsoft.AspNetCore.All`
4. Restore

Expected behavior: Error of some kind

Actual behavior: It references the package "successfully" but silently fails to bring in any types.

We have a `build\PublishWithAspNetCoreTargetManifest.targets` file, which means NuGet thinks the package is supported by all frameworks (with a special targets file for `netcoreapp2.0`). We should put that file in `build\netcoreapp2.0` so NuGet will see that there are no assets for any other framework.

Also, we need to verify that NuGet does actually disallow installing it in that circumstance. It's possible it won't disallow it, just won't reference the targets files. In that case, we could put a fallback targets file with an error message.

**Comment by JunTaoLuo** [comment]
I copied this pattern from https://github.com/aspnet/Configuration/blob/1e39e9b20c85c95017b14992a55e2c7f606e6d73/src/Microsoft.Extensions.Configuration.UserSecrets/build/netstandard1.3/Microsoft.Extensions.Configuration.UserSecrets.targets.
We might want to revisit that as well.

**Comment by JunTaoLuo** [comment]
Seems like simply moving the targets file to netcoreapp2.0 does not prevent the package from being referenced from an app targeting net461. We will likely need to add a default target that gives an error of some kind.

**Comment by muratg** [comment]
@natemcmaster If we can't get to this in 2.0.0, it's OK to punt.

**Comment by natemcmaster** [comment]
Actually, the build target layout is not the problem. The real issue is that there was no `lib` asset. Therefore NuGet will install it into anything.
