### ISSUE TITLE
Validate the fix for Microsoft.Win32.Registry version mismatch in the store [https://github.com/dotnet/sdk/issues/1162]

### ISSUE THREAD

**Issue by muratg** [aspnet/MetaPackages#144]
The check-in went in, but we didn't validate it yet.

**Comment by JunTaoLuo** [comment]
I have verified that when we reference a version of M.Win32.Registry (or any other component of the shared framework) that is different from the one included in the current shared framework, it is included in the store output as well as the artifacts.xml. Closing as fixed.
