### ISSUE TITLE
Experience: Duplicate console logs

### ISSUE THREAD

**Issue by moozzyk** [aspnet/MetaPackages#162]
With people used to configuring logging in the code the following code:

```
            WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging(c => c.AddConsole().SetMinimumLevel(LogLevel.Debug))
                .UseStartup<Startup>()
                .Build();
```
 results in a behavior that might be surprising (duplicate and mangled (see: dbugdbug) logs)
```
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
dbugdbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[4]
      Hosting started
: Microsoft.AspNetCore.Hosting.Internal.WebHost[4]
      Hosting started
Hosting environment: Development
Content root path: C:\Users\pawelka\Source\Repos\WebAppCoreTest\WebAppCoreTest
Now listening on: http://localhost:50163
Application started. Press Ctrl+C to shut down.
dbugdbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[0]
      Loaded hosting startup assembly WebAppCoreTest
: Microsoft.AspNetCore.Hosting.Internal.WebHost[0]
      Loaded hosting startup assembly WebAppCoreTest
```

This is because the CreateDefaultBuilder method already add Console logger. Creating a new one with more detailed logging level results in having two console loggers. I think people may run into this. 

I would also argue that having more than one Console logger registered is rarely (if ever) correct.

**Comment by pakrym** [comment]
`SetMinimumLevel` is not specific to `AddConsole` and sets the global level. You can do `.ConfigureLogging(c => c.SetMinimumLevel(LogLevel.Debug))` or `ConfigureLogging(c => c.WithFilter<ConsoleLoggerProvider>(LogLevel.Debug))`

**Comment by moozzyk** [comment]
@pakrym  - this is why the bug is about experience - it is just confusing

**Comment by Li-ReDBox** [comment]
@moozzyk thank you for pointing out the problem. This is indeed confusing. Also, `dbug` and `dbugdbug` add extra layer of confusing. I don't know why the normally used `debug` appears as `dbug` here. As a new developer to asp.net, I have not found a clear answer of what `AddDebug()` means to me: where is its target? Do I need some special tool to capture messages? What is it exactly for? Do I need it?

**Comment by QuantumHive** [comment]
Coming from `aspnetcore 1.1`, this is indeed confusing. All this time I had duplicate logging, because in my `Startup` file I still had `loggerFactory.AddConsole()` configured. I didn't know what the default builder did, but in the [migration docs](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/index#update-main-method-in-programcs) it is adviced to use the default builder, while not mentioning that this actually adds potential duplicate logging.

**Comment by muratg** [comment]
Hit this yesterday :)  

@pakrym / @moozzyk -- is there a way to detect this is happening?  We can consider emitting a warning for some loggers I think.

**Comment by pakrym** [comment]
We can change loggers to call `TryAddEnumerable` so another instance won't be added if called twice 

/cc @davidfowl

**Comment by StefanFrederiksen** [comment]
So is there a way to workaround this by using the default builder, but changing the logging configurations?
