### ISSUE TITLE
Add E2E tests for shared framework

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/MetaPackages#166]
We don't have any automated tests that verify basic scenarios work with the runtime store we produce.

Scenarios:
 - `dotnet new mvc && dotnet publish` passes
 - `dotnet new mvc && dotnet publish && dotnet app.dll` launches web app successfully
 - ~~`dotnet publish /p:PublishWithAspNetCoreTargetManifest=false` does not trim (Important because this is our escape-hatch if something goes wrong after a release)~~ n/a in 2.1

/cc @JunTaoLuo @mikeharder

**Comment by muratg** [comment]
@jkotalik Lower priority than ANCM and middleware work, but we should try to get this done after those.

**Comment by natemcmaster** [comment]
@mikeharder wrote a bunch of functional tests in https://github.com/mikeharder/AspNetCoreSdkTests. Would be good to move these into the main repo.

**Comment by natemcmaster** [comment]
Correct.

**Comment by natemcmaster** [comment]
This work is done now.
