### ISSUE TITLE
sqlite not trimmed during publish

### ISSUE THREAD

**Issue by mikeharder** [aspnet/MetaPackages#171]
# Repro Steps
1. `dotnet new web`
2. `dotnet publish`

# Expected
publish dir contains only app binaries/config

# Actual
```
x64\e_sqlite3.dll
x86\e_sqlite3.dll
```

# Dependency Versions
* CLI: https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview2-006494/dotnet-sdk-2.0.0-preview2-006494-win-x64.zip

# Notes
This may be fixed when SQLite is updated to 1.1.6 or later.

**Comment by JunTaoLuo** [comment]
Dup of https://github.com/aspnet/Microsoft.Data.Sqlite/issues/360
