### ISSUE TITLE
Test reliability: WebHostFunctionalTests fail if port 5000 is already in use

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/MetaPackages#183]
WebHostFunctionalTests.CreateDefaultBuilder_InitializeWithDefaults 
http://aspnetci/viewLog.html?buildId=253606&tab=buildResultsDiv&buildTypeId=Lite_MetaPackages
```
Unable to start Kestrel.
Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer 
Information: 
dotnet stdout: System.IO.IOException: Failed to bind to address http://127.0.0.1:5000: address already in use. 
---> Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.AddressInUseException: Error -4091 EADDRINUSE address already in use 
---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4091 EADDRINUSE address already in use
```

**Comment by Tratcher** [comment]
HttpSys has a test for default port with the same problem. Last time it was cased by a stale dotnet.exe process from an MVC test. Something is wrong with the "kill all process after testing" failsafes we added.

**Comment by natemcmaster** [comment]
It appears the process that is still running is coming from aspnet/websdk. It doesn't get killed because it is a standalone process so its exe name doesn't match any pattern we have our kill step.

**Comment by natemcmaster** [comment]
Found the offending zombie process and nuked it. We should still try to make these tests more reliable by using random ports. Contention on port 5000 is a frequent source of failure.

**Comment by Tratcher** [comment]
These tests are supposed to test the defaults, using a random port would defeat the point. We may just have to remove them.

**Comment by muratg** [comment]
If we're still hitting this frequently enough, we'll bring this issue back from backlog. And look into finding a solution that for other repos as well.

**Comment by natemcmaster** [comment]
Closing as this bug is stale. RAAS will open issues for test failures in the future. This does not appear to be a frequent problem.
