### ISSUE TITLE
Use packages.csv to generate the project file of Microsoft.AspNetCore.All

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/MetaPackages#19]
Most of the information from M.A.All comes from the packages.csv so to reduce duplication, we should generate the project file from it.

**Comment by JunTaoLuo** [comment]
This needs to be higher priority or we need to add a verification step in our build to guarantee issues like https://github.com/aspnet/MetaPackages/issues/157 do not occur again. The wiki on Coherence-Signed is not sufficient.

**Comment by muratg** [comment]
@JunTaoLuo Moving to 2.1, but we can try doing this even after we close 2.0.0 for other check-ins.

**Comment by natemcmaster** [comment]
Would be great to also verify Archive.AspNetCore.All. We just found a few more packages that should have been in Archive.AspNetCore.All but were left out for unknown reasons.

**Comment by JunTaoLuo** [comment]
Completed in 2.0.3 with artifacts.props see https://github.com/aspnet/Universe/pull/565. We will be porting this back to dev at some point. Marking as done but will close once it's in dev.

**Comment by JunTaoLuo** [comment]
Changes in dev pending decision on future of runtime store
