### ISSUE TITLE
The Microsoft.AspNetCore.All meta package is missing the TestHost package

### ISSUE THREAD

**Issue by davidfowl** [aspnet/MetaPackages#191]
Seems like a strange omission https://twitter.com/leastprivilege/status/884694960251031553.

/cc @JunTaoLuo @Eilon @muratg

**Comment by Tratcher** [comment]
Do we recommend the .All metapackage for test projects?

**Comment by MichaCo** [comment]
@Tratcher maybe a Microsoft.AspNetCore.AllTest meta package containing all the things needed from *.All + Test stuff?

**Comment by JunTaoLuo** [comment]
It was a concious decision to not include test packages, see https://github.com/aspnet/MetaPackages/issues/21#issuecomment-295518536. We can discuss whether test packages should be included though.

**Comment by Eilon** [comment]
Yeah it would strike me as odd to have test-only stuff in the default app package graph...

**Comment by JunTaoLuo** [comment]
We spoke about this a while ago and the decision was to not include the test packages so I think we can close this one @Eilon @davidfowl @muratg
