### ISSUE TITLE
Need to add Debian 9 packages

### ISSUE THREAD

**Issue by wli3** [aspnet/MetaPackages#196]
dotnet-sdk depends on store package on Debian, so Debian 9 store package is needed

dotnet/cli#7184

**Comment by JunTaoLuo** [comment]
I'm assuming this is in addition to the debian packages we produce now?

**Comment by wli3** [comment]
Correct, I believe it is debian 8, and the existing package will not work for debian 9, @Petermarcu right?

**Comment by JunTaoLuo** [comment]
Yea, I believe the existing packages are for debian 8.2

**Comment by Petermarcu** [comment]
Correct. We have to have a new .deb for the runtime so everything upstack will need a new deb that expresses a runtime dependency.

**Comment by JunTaoLuo** [comment]
@Eilon We'll need this for 2.0.0

**Comment by Petermarcu** [comment]
We may end up needing to build all the packages by hand once we have the final build if we can't get all the infra in place and then add the infra in servicing. We're discussing that from the bottom up.

**Comment by Eilon** [comment]
Ok.

**Comment by wli3** [comment]
@Petermarcu I would prefer not one off, it will be very stressful for dotnet-sdk package since it has most dependencies and there will be the most narrow window to produce. Also, "one off" doesn't mean it will be done only once.

**Comment by Petermarcu** [comment]
Its looking like the existing ASP.NET packages may just work and will just need to be put in the debian9 feed when its available. We're still digging.

**Comment by wli3** [comment]
We did test on Debian 9 with SDK without modify, it worked, closing this issue
@jbeisner  FYI
