### ISSUE TITLE
Targeting netcoreapp2.0 - Why?

### ISSUE THREAD

**Issue by Mardoxx** [aspnet/MetaPackages#198]
Why does this target netcoreapp2.0 whereas other netcore libraries target netstandard2.0?

**Comment by Mardoxx** [comment]
>Note, the Microsoft.AspNetCore.All metapackage will only ever target netcoreapp2.0, as it relies on features of .NET Core as you'll see. IF you are targeting .NET Framework, then you will still be able to use the individual ASP.NET Core packages (as they will target netstandard2.0, it is just the metapackage that will not be available.

Oh okay.

**Comment by JunTaoLuo** [comment]
Correct, the Microsoft.AspNetCore.All metapackage is only intended to be used on .NET Core.
