### ISSUE TITLE
Map named ASP.NET target manifest property to the corresponding file path

### ISSUE THREAD

**Issue by bleroy** [aspnet/MetaPackages#20]
Handle "ASP.NET/2.0.0" `TargetManifest` values from the project file, and map them to the path of the corresponding manifest file.

**Comment by Eilon** [comment]
The "big" metapackage should have a new .targets file in it that auto-enables the project referencing it to use the included target manifest file (which lists all the packages that are in the cache) when the app is published. The .targets file should have an optional switch `PublishWithAspNetCoreTargetManifest` to turn the feature off.

When `PublishWithAspNetCoreTargetManifest` is enabled, the targets file will determine the path to the enclosed target manifest file and set it on the `<TargetManifest>` MSBuild property, which will get used by the publishing process. We need to figure out the right MSBuild target in which this should run - something like `BeforePublish` (don't know the exact name).

1. We could start out with an empty manifest file just to get the MSBuild authoring complete in the .targets file.
2. Then when the package cache is done and publishing to the feed, we can put real XML in the manifest and have it work end-to-end.

**Comment by bleroy** [comment]
Note that it is possible from the CLI's `publish` command to specify multiple target manifests. The `TargetManifest` tag in the project file should probably also support multiple manifests, which means that this feature should be able to handle "ASP.NET/2.0.0" even when it's not the whole value.

**Comment by JunTaoLuo** [comment]
Targets have been added, will modify the build to add the manifests to the package.
