### ISSUE TITLE
UseIISIntegration at WebHost.CreateDefaultBuilder used by default for other platforms

### ISSUE THREAD

**Issue by luisgizirian** [aspnet/MetaPackages#209]
Is it by design or does it affect somehow, calling UseIISIntegration when Apache or NGINX (to mention others) is used?

Using AspNetCore 2 preview 2.

https://github.com/aspnet/MetaPackages/blob/rel/2.0.0-preview2/src/Microsoft.AspNetCore/WebHost.cs

Please advice.
Luis

**Comment by Tratcher** [comment]
It's harmless, it only activates when run in IIS (via specific environment variables).

**Comment by luisgizirian** [comment]
Thanks for your quick reply @Tratcher. I'm going though proxy issues on another platform and was wondering if could be related.

Back to topic, are there specifics that could be configured by default as well for NGINX or Apache?

**Comment by Tratcher** [comment]
Yes, some of the assumptions made by UseIISIntegration could also be made for a similar UseNginxIntegration.
https://github.com/aspnet/Hosting/issues/815#issuecomment-279238728

The main reason we haven't created something like that is that NGinx usually doesn't boot up your process, unlike our IIS hosting.

@shirhatti One more ask for UseNginxIntegration.

**Comment by luisgizirian** [comment]
Thanks @Tratcher ! I'm closing this down.
