### ISSUE TITLE
WebHost.CreateDefaultBuilder(args) should populate WebHost config from args

### ISSUE THREAD

**Issue by halter73** [aspnet/MetaPackages#221]
aspnet/KestrelHttpServer#1998 brought this issue to my attention. I posted a fairly simple workaround there.

It would be more intuitive to populate the WebHostBuilder config/settings in addition to [the app config](https://github.com/aspnet/MetaPackages/blob/f67292cf22577a45e15eb91bfa4e69e7eacf7bf0/src/Microsoft.AspNetCore/WebHost.cs#L177) with the args passed into `WebHost.CreateDefaultBuilder(args)`.

This would make `dotnet run --urls "http://localhost:5001"` work out of the box.

**Comment by leak** [comment]
Does this include populating config from the appconfig.json?

As mentioned here https://github.com/aspnet/Hosting/issues/1230

**Comment by halter73** [comment]
@leak In the meantime, I recommend using the workaround suggested in https://stackoverflow.com/a/44118610/719967.

**Comment by dasMulli** [comment]
I'm assuming this is the reason why `--environment Development` and similar also doesn't do much? this would be great to have when deploying windows services for different environments where setting env vars is hard.

**Comment by Tratcher** [comment]
@dasMulli yes.
Here's the workaround from the linked issue:
```
public static IWebHost BuildWebHost(string[] args)
{
    var configuration = new ConfigurationBuilder().AddCommandLine(args).Build();

    return WebHost.CreateDefaultBuilder(args)
        .UseConfiguration(configuration)
        .UseStartup<Startup>()
        .Build();
}
```
