### ISSUE TITLE
Microsoft.AspNetCore.All cannot be used from net47

### ISSUE THREAD

**Issue by mjrousos** [aspnet/MetaPackages#222]
Since ASP.NET Core packages generally target .NET Standard 2.0, the product can work on NetCore, NetFx, or Mono.

However, the Microsoft.AspNetCore.All package is still targeting netcoreapp2.0, so it can't be used when the project's target framework is net47. I've confirmed that replacing Microsoft.AspNetCore.All with the individual ASP.NET Core packages works when targeting Net47, but it would be very convenient to be able to use the metapackage in that scenario.

**Comment by JunTaoLuo** [comment]
Please refer to https://github.com/aspnet/MetaPackages/issues/198.

**Comment by mjrousos** [comment]
Ah, I see. Out of curiosity, what netcoreapp2.0-specific features does Microsoft.AspNetCore.All depend on?

**Comment by Tratcher** [comment]
It depends on the presence of `C:\Program Files\dotnet\store\x64\netcoreapp2.0` on the dev and production machines.

**Comment by mjrousos** [comment]
On production machines, too? Does that mean we shouldn't use the meta-package if deploying [self-contained](https://docs.microsoft.com/en-us/dotnet/core/deploying/#self-contained-deployments-scd)?

**Comment by Tratcher** [comment]
There's a publish opt-out flag for self-contained scenarios. @JunTaoLuo can provide the details.

**Comment by mjrousos** [comment]
Cool, thanks for the information!

**Comment by JunTaoLuo** [comment]
By default, self-contained apps do not trim publish output so you don't have to explicitly disable it in that scenario. To disable publish output trimming for platform dependent apps, you can set the `PublishWithAspNetCoreTargetManifest` property to `false` in your project file.

**Comment by JunTaoLuo** [comment]
I'm closing this issue as the question has been answered and there are no action items.
