### ISSUE TITLE
Potentially misleading documentation comment for WebHost.CreateDefaultBuilder

### ISSUE THREAD

**Issue by onyxmaster** [aspnet/MetaPackages#223]
Hi!
The [documentation comment](https://github.com/aspnet/MetaPackages/blob/c920c459537c21285b47b05f033a48363297e3dc/src/Microsoft.AspNetCore/WebHost.cs#L148) mentions that `CreateDefaultBuilder(string[] args)` "adds the developer exception page when IHostingEnvironment.EnvironmentName is 'Development'". If I understand correctly, this is usually done by `Startup.Configure(IApplicationBuilder)`. I believe this documentation comment should be improved.

**Comment by JunTaoLuo** [comment]
Good catch. We used to have the developer exception page middleware added by default in a development environment by adding a startup filter but that was removed in https://github.com/aspnet/MetaPackages/pull/95. However, we neglected to update the documentation to reflect the removal.
