### ISSUE TITLE
Same key form the second JSON source is ignored

### ISSUE THREAD

**Issue by Li-ReDBox** [aspnet/MetaPackages#230]
I load two json files in BuildWebHost like this:

```
            .ConfigureAppConfiguration((ctx, config) =>
                config.AddJsonFile("version1.json"))
                .AddJsonFile("version2.json"));
    ....
```
In version1.json:
```js
{ "key": "version1"}
```
In version2.json
```js
{ "key": "version2"}
```
I have tried `optional` to be `true` or `false`, in neither case, the key-value pair from version2.json is loaded without switching order. 

My understanding is that for the same key the latest value wins. Why cannot I get that result?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Configuration#723
