### ISSUE TITLE
Can't install dotnet-sdk nightly from debian feed

### ISSUE THREAD

**Issue by wli3** [aspnet/MetaPackages#231]
_From @bazzilic on September 7, 2017 12:42_

## Steps to reproduce
I am trying to install dotnet SDK nightly build on a clean ubuntu 16.04, so I run this as per README.md:

```
echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list     && \
apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893 && apt-get update                                        && \
apt-get install -y $(apt-cache search dotnet-sdk | tail -n 1 | cut -d' ' -f1)
```

## Expected  behavior
Dotnet SDK install nicely.

## Actual behavior
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1.0-preview1-007172 : Depends: aspnetcore-store-2.1.0-preview1-26623 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Looking through `apt-cache search asp` shows that there are no packages at all named `aspnetcore-store`. An extensive googling for a debian feed I might be missing resulted in nothing, I couldn't even find what repo this package builds from.

Any ideas? Thanks.

## Environment data
Clean ubuntu 16.04 xenial (in a docker container).

_Copied from original issue: dotnet/cli#7609_

**Comment by wli3** [comment]
Hi @bazzilic thank you for the post. 

Although the upload of package dotnet-sdk-* is stable after recent change, aspnetcore-store is absent from the feed. Move this issue to store repo

**Comment by wli3** [comment]
hi @JunTaoLuo @joeloff we talked about adding daily feed for store package. We need aspnet-store package to be in the feed in order to complete the scenario above.

I added a C# client/msbuild task for the feed with retry logic, so far the upload is very stable. You can use it as reference
https://github.com/dotnet/cli/pull/7460

**Comment by tasoss** [comment]
Hello.I'm having the same problem 

> The following packages have unmet dependencies:
 dotnet-sdk-2.1.0-preview1-007186 : Depends: aspnetcore-store-2.1.0-preview1-26623 but it is not installable

but i don't see how this is resolved?

**Comment by wli3** [comment]
Hi @JunTaoLuo @joeloff @muratg, is there any update on this issue? Daily feed is still blocked by it cc: @livarcocc

**Comment by JunTaoLuo** [comment]
Haven't prioritized this as our efforts have been focused on reworking our 2.0.x servicing build infrastructure. @muratg @Eilon to decide if we want to bump the priority of this task.

**Comment by markusr** [comment]
Any update on this? This is blocking me to do: https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm

**Comment by muratg** [comment]
@JunTaoLuo Are we just missing the nightly installer for Debian?  IoW do we still produce generic .tar.gz's?

**Comment by JunTaoLuo** [comment]
We should investigate how to publish our installers to the debian feeds. We produce the generic .tar.gz's but we do not publish it anywhere that's publicly available.

**Comment by markusr** [comment]
Sorry for asking again. But this is still open. I would really like to test remote debugging.

**Comment by leecow** [comment]
@wli3 - ASP team needs to publish their part of the install to the existing feed. Could this step possibly be added to your code the publishes the CLI? 

cc @JunTaoLuo

**Comment by wli3** [comment]
@leecow I will be hard to maintain. To keep up with the normal insertion need effort already. Also, it is strange for CLI to publish asp.net's package.

**Comment by JunTaoLuo** [comment]
We will retriage this item for preview 2. cc @muratg @Eilon

**Comment by muratg** [comment]
@JunTaoLuo how much work is left on this one?

**Comment by JunTaoLuo** [comment]
I'll get to it this week, I need to port over @wli3's implementation for uploading to the debian nightly feed as well as get the proper credentials for the actual push.

**Comment by JunTaoLuo** [comment]
Quick :up::date: I have the code in a branch right now but I can't proceed further until I have the push credentials to the debian feed. I have sent an email for this so as soon as I hear back I'll start on this again.

**Comment by JunTaoLuo** [comment]
@leecow @wli3 Can one of you confirm that we no longer plan to publish debian installers to daily feeds? The offline discussion in the email threads seems to point towards direct downloads of debian installers from the azure blobs.

**Comment by JunTaoLuo** [comment]
Confirmed that this is not needed.
