### ISSUE TITLE
Add SignalR to the metapackage

### ISSUE THREAD

**Issue by davidfowl** [aspnet/MetaPackages#235]
It's not there and it should be by now.

/cc @JunTaoLuo @muratg @moozzyk @natemcmaster

**Comment by muratg** [comment]
Yes, only on the dev branches though (for 2.1).

**Comment by moozzyk** [comment]
I think we will need to do this for preview.

**Comment by JunTaoLuo** [comment]
Note that we are moving from packages.csv to artifacts.props pending https://github.com/aspnet/Universe/pull/566. Instructions will be updated but the jist of it is to mark signalr packages as Category="ship" Metapackage="true"

**Comment by muratg** [comment]
@anurse feel free to close one of the issues.
