### ISSUE TITLE
Stop adding CommandLine configuration provider twice

### ISSUE THREAD

**Issue by glennc** [aspnet/MetaPackages#243]
In the CreateDefaultBuilder method we appear to add the CommandLine provider twice:

 1. https://github.com/aspnet/MetaPackages/blob/fcdd25635c8174a0c8a7a0853a6f3d8620448839/src/Microsoft.AspNetCore/WebHost.cs#L173
 2. https://github.com/aspnet/MetaPackages/blob/fcdd25635c8174a0c8a7a0853a6f3d8620448839/src/Microsoft.AspNetCore/WebHost.cs#L190

**Comment by Tratcher** [comment]
For reference, 173 existed first. Then we added 190 so hosting/kestrel could get them. That said, do we keep this order just because we want them to override the other providers?

**Comment by glennc** [comment]
Ahh. We add it again so that they will overwrite any other config options even though they are also added first. Right?

**Comment by JunTaoLuo** [comment]
I think this was more of an oversight than a conscious decision. I think it makes more sense to remove the command line provider at 173. If the command line args are overwritten, we should preserve that for the application instead of restoring the initial values.

**Comment by Tratcher** [comment]
There has been much debate over the precidence of each config source. Also, changing it is potentially breaking.

**Comment by glennc** [comment]
Closing this. It's just jarring, not necessarily wrong by the sound of it.
