### ISSUE TITLE
Support .NET Framework apps using Microsoft.AspNetCore.App & Microsoft.AspNetCore.All

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/MetaPackages#258]
This is predicated on the .NET linker being updated in 2.1 to properly support **not** trimming required ASP.NET Core modules that might not be directly called by the application but are otherwise required to function (i.e. it roots them by default), along with supporting applications targeting .NET Framework.

**Comment by muratg** [comment]
@DamianEdwards was this for the investigation @JunTaoLuo did? Anything left?

**Comment by muratg** [comment]
@DamianEdwards *ping* Good to close?

**Comment by DamianEdwards** [comment]
Not yet, talking to Richard about this still

**Comment by muratg** [comment]
@DamianEdwards Still keep in the milestone?

**Comment by DamianEdwards** [comment]
Can move to RC. @richlander is working on the blocker.

**Comment by Eilon** [comment]
@DamianEdwards / @richlander - any update on this? Time for RC1 is running out.

**Comment by muratg** [comment]
@DamianEdwards Removed from the milestone. Retriage as needed.

**Comment by natemcmaster** [comment]
Now that we've announced deprecation of .NET Framework support in 3.0, I'm assuming this is no longer important. Closing. If there is still an action item here for 2.x, please reopen an issue on the the repo, https://github.com/aspnet/AspNetCore

https://github.com/aspnet/AspNetCore/issues/3753
