### ISSUE TITLE
Microsoft.AspNetCore.App is not specifying version ranges for 3rd party dependencies

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/MetaPackages#259]
It seems that *Microsoft.AspNetCore.App* is not currently setting version ranges for the 3rd party dependencies in the transitive graph, e.g. *Newtonsoft.Json*.

Do folks think we should instead be locking these versions to the known good version, given the intent is to ensure folks can't be lifted out of the supported state without a warning (direct reference) or error (transitive lifting)? My gut is saying we should be limiting these too.

Thoughts @davidfowl @JunTaoLuo @Eilon ?

**Comment by JunTaoLuo** [comment]
Yes we should, I thought I filed a bug for this in preview2 since we were running out of time for preview1 but I can no longer find it. I'll move this issue to Universe.

**Comment by JunTaoLuo** [comment]
This issue was moved to aspnet/Universe#920
