### ISSUE TITLE
Generate api check baseline for Microsoft.AspNetCore

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/MetaPackages#37]
Once we release the WebHost static APIs, we should generate an API baseline.

**Comment by muratg** [comment]
Good call! The APIs are new in 2.0.0, so we can do this in 2.0.0 RTM and start to catch breaking changes after that.

**Comment by muratg** [comment]
This will be a "new package" in 2.0.0, so technically we only care about breaking changes after 2.0.0 is done. Moving to 2.1.
