### ISSUE TITLE
Ensure logger factory is initialized with default configuration section in WebHost.CreateDefaultBuilder

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/MetaPackages#45]
We basically need to add a call to `logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));` at https://github.com/aspnet/MetaPackages/blob/dev/src/Microsoft.AspNetCore/WebHost.cs#L167

@glennc @JunTaoLuo @BrennanConroy

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/MetaPackages/issues/54
