### ISSUE TITLE
Produce Linux package store as a tarball instead of zip

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/MetaPackages#48]
Our docker images don't have `unzip` installed. If we produce a tarball instead, then we can use `tar` to extract the package cache.

cc @JunTaoLuo

**Comment by natemcmaster** [comment]
cref https://github.com/aspnet/aspnet-docker/blob/99cda5101970dff0b0e32845ee8dd8bc4633da9e/2.0/jessie/runtime/Dockerfile#L11-L13

**Comment by DamianEdwards** [comment]
Are you referirng to the runtime store? It's supposed to be a tar.gz as captured at https://github.com/aspnet/Coherence-Signed/issues/428#issuecomment-296279747

**Comment by natemcmaster** [comment]
Yes, I meant "store".

**Comment by natemcmaster** [comment]
We already had code to do this in another repo. @JunTaoLuo checkout

https://github.com/aspnet/Coherence-Final/blob/dev/packaging/targets/packagecache.targets#L250-L261
and  https://github.com/aspnet/Coherence-Final/blob/dev/scripts/zip2tgz.sh

**Comment by natemcmaster** [comment]
Wrong build step. The zip file we use is actually produced in our signing steps, not here.
