### ISSUE TITLE
Publish output not trimmed when referencing Microsoft.AspNetCore.All

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/MetaPackages#50]
After the target was added in https://github.com/aspnet/MetaPackages/issues/20. It is not currently trimming the publish output.

**Comment by DamianEdwards** [comment]
Seems the property name we need to set is `<TargetManifestFiles>`. If we're not already we'd need to ensure we're merging with existing value, etc.

**Comment by JunTaoLuo** [comment]
cc @kichalla this will unblock you once it goes through the build

**Comment by kichalla** [comment]
Great. thanks
