### ISSUE TITLE
Resolve which manifest to trim publish output

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/MetaPackages#57]
In #55, we are now trimming by all manifests. This is due to a few limitations:

1. dotnet sdk publish targets resolves manifest files as a global item group so we need to set the `TargetManifestFiles` property in a global property group to ensure it is used. The dotnet sdk should be resolving the list of manifest files in the targets which uses them (will file a bug for this).
2. There is no cross-platform backwards compatible way of determining the os and platform outside of an MSBuild target.

Though in theory, trimming by all manifests should be correct, we may want to be more specific with which manifest to trim by in the future. If we decide to keep this behaviour, we should at least consolidate all manifests into a singular file.

**Comment by DamianEdwards** [comment]
This seems to be unblocked now that https://github.com/dotnet/sdk/issues/1164 is complete. Can we do this for preview2?

**Comment by JunTaoLuo** [comment]
The most preferable approach here may be to merge the manifests into one. Will reconsider after preview2 since this isn't critical and only affects the error message when no store is installed.

**Comment by muratg** [comment]
@JunTaoLuo do we need to finish this in 2.0.0, or good to move?

**Comment by JunTaoLuo** [comment]
The error message is rather verbose but there is no functional impact. I'll move it out if I can't get to it by next week. We can make the change post 2.0.0 if necessary.

**Comment by JunTaoLuo** [comment]
@muratg suggest we punt this.

**Comment by JunTaoLuo** [comment]
In https://github.com/aspnet/Universe/pull/565, we have added consolidation of the manifests. Now there will be one manifest: `aspnetcore-store-2.0.3-rtm-71.xml` or `aspnetcore-store-2.0.3.xml` for the no timestamp version.
