### ISSUE TITLE
Exception when UserIdSecrets isn't turned on in the project file

### ISSUE THREAD

**Issue by davidfowl** [aspnet/MetaPackages#60]
I created a 1.1.1 template and upgraded to 2.0 and used the new API the got this error:

![image](https://cloud.githubusercontent.com/assets/95136/25427879/c82248aa-2a28-11e7-9ca1-b55ea6938536.png)

It's pretty awful that this throws like that by default. Is there any way to avoid this exception and have it noop (like the other config providers do) if the application isn't configured for user secrets?

/cc @natemcmaster

**Comment by natemcmaster** [comment]
What is in the template? IMO if template calls user secrets in C#, it should also scaffold the property in csproj.

**Comment by DamianEdwards** [comment]
The new templates do, but the old empty template didn't, which is why you're seeing this. Are you thinking we just change this to log a warning instead of throwing?

**Comment by natemcmaster** [comment]
There is no logging available from ConfigurationBuilder

**Comment by davidfowl** [comment]
> The new templates do, but the old empty template didn't, which is why you're seeing this. Are you thinking we just change this to log a warning instead of throwing?

I'm thinking it should n00p completely and not add the configuration provider. Just like the other configuration providers do.

**Comment by DamianEdwards** [comment]
Ok so add an `bool optional` param overload then, and leave default as false, and set to true in `WebHost`

**Comment by natemcmaster** [comment]
Fixed in #64
