### ISSUE TITLE
Remove assembly from metapackage.

### ISSUE THREAD

**Issue by pakrym** [aspnet/MetaPackages#7]
Microsoft.AspNetCore.dll should not be in the package.

@pranavkm @davidfowl @BrennanConroy

**Comment by pranavkm** [comment]
Weird. I thought we fixed this

**Comment by pakrym** [comment]
Just built it locally, dll is inside. Am I doing something wrong?

**Comment by muratg** [comment]
Yeah, in the actual nupkg that CI generated, there's no dll. Basically an empty package.
