### ISSUE TITLE
Kestrel config binder should understand * and localhost

### ISSUE THREAD

**Issue by Tratcher** [aspnet/MetaPackages#73]
The templates are going to enable SSL via config in dev and production. They need to set up the rest of the endpoints when they do this. https://github.com/aspnet/MetaPackages/pull/44 added the ability to bind to IPs and ports, but that makes for a poor user experience. In dev the templates want localhost, but will have to specify 127.0.0.1 (and ::1) if they want IPv6 support. In production they'll need to specify a public IP (0.0.0.0 and ::0).

Config should allow `localhost` that binds to 127.0.0.1 and ::1, and * that binds to 0.0.0.0 and ::0, using the same logic that kestrel applies to UseUrls values. Even better, implement this in Kestrel with a Listen that takes the string ip/host so you don't have to duplicate all of the logic.

**Comment by Tratcher** [comment]
@danroth27

**Comment by danroth27** [comment]
@muratg @DamianEdwards @Eilon We chatted about this one and we think we need to get this into preview1. @muratg please assign.

**Comment by danroth27** [comment]
We chatted *even more* and the fix is more complicated than we want to take right now. We'll have to tell folks to browse to localhost.

**Comment by muratg** [comment]
Assigning to @cesarbs for post preview2.

**Comment by danroth27** [comment]
@glennc This issue is also the first in a series of issue that prevents enabling docker for out templates that use authentication.

**Comment by Tratcher** [comment]
Note this code is moving to Kestrel. https://github.com/aspnet/KestrelHttpServer/pull/1878

**Comment by danroth27** [comment]
This issue was moved to aspnet/KestrelHttpServer#1879
