### ISSUE TITLE
Move CertificateLoader to a new config package

### ISSUE THREAD

**Issue by danroth27** [aspnet/MetaPackages#81]
Proposal: Microsoft.Extensions.Configuration.Certificates

**Comment by danroth27** [comment]
@muratg @javiercn We need to use the CertificateLoader to load the signing certificate for ASP.NET Core Identity scenarios, but we shouldn't need to take a dependency on this meta package to do so. We need to get the CertificateLoader moved to someplace more reasonable. This is blocking the default config schema work for preview2.

**Comment by muratg** [comment]
@javiercn any proposals for a repo? Is Configuration the right repo?  @danroth27 I assume you'd like this in preview2?

cc @ajcvickers @DamianEdwards

**Comment by Tratcher** [comment]
Proposal: Hosting. Kestrel and Identity are the primary consumers.
Name: Microsoft.AspNetCore.Certificates.Configuration

**Comment by muratg** [comment]
That sounds good to me.  @danroth27 you OK with that name/namespace?
