### ISSUE TITLE
Cannot publish a web app when using unsigned version of Microsoft.AspNetCore.All

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/MetaPackages#89]
**Repro**
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview1-24785" />
  </ItemGroup>
</Project>
```

dotnet restore
dotnet publish

**Expected**
Publish works.

**Actual**
Publish fails.
```
/usr/share/dotnet/sdk/2.0.0-preview2-005905/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(252,5): error MSB4018: The "ResolvePublishAssemblies" task failed unexpectedly. [/app/app1
493666299.csproj]
/usr/share/dotnet/sdk/2.0.0-preview2-005905/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(252,5): error MSB4018: System.IO.FileNotFoundException: Could not find file '/root/.nuget/
packages/microsoft.aspnetcore.all/2.0.0-preview1-24785/build/manifest.win-x64.xml'. [/app/app1493666299.csproj]
/usr/share/dotnet/sdk/2.0.0-preview2-005905/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Publish.targets(252,5): error MSB4018: File name: '/root/.nuget/packages/microsoft.aspnetcore.all/2.0.0-pr
eview1-24785/build/manifest.win-x64.xml' [/app/app1493666299.csproj]
```

**Comment by JunTaoLuo** [comment]
You need to use the .All package from signed feeds. We should re-organize our build chain so we push packages at the end of Coherence-PackageCache instead of Coherence to the unsigned feeds.

**Comment by natemcmaster** [comment]
Ping. Just hit this again with preview2 stuff. It makes doing sign off hard when the signed :-(

**Comment by natemcmaster** [comment]
The error may go away preview3 bits now that we use globbing to find the manifest files, right @JunTaoLuo? But this means the unsigned package won't get the trimming feature.

**Comment by JunTaoLuo** [comment]
Correct, the unsigned package does not do trimming. I attempted to publish unsigned metapackage earlier but ran into a few issues, see https://github.com/aspnet/MetaPackages/pull/123. I don't think there's a quick fix here and it will require some more re-organization of our builds.

**Comment by Eilon** [comment]
Not a high priority to have this package work on this feed.
